AI_RISK_PATTERNS = [
    ('Prompt Injection Risk',
     r'(?i)(system_prompt|system_message).*\+\s*.*user',
     'CRITICAL',
     'User input directly in system prompt = injection risk'),
    ('Unvalidated LLM Input',
     r'(?i)(openai|anthropic|llm).*(complete|message).*user_input',
     'HIGH',
     'User input to LLM without sanitize = dangerous'),
    ('Password Logged',
     r'(?i)(print|log|logger).*password',
     'HIGH',
     'Password logged = credential leak risk'),
    ('Token Logged',
     r'(?i)(print|log|logger).*(token|api_key|secret)',
     'HIGH',
     'Sensitive data exposed in logs'),
    ('Subprocess shell=True',
     r'subprocess\.(call|run|Popen).*shell\s*=\s*True',
     'CRITICAL',
     'shell=True allows command injection'),
    ('os.system Usage',
     r'os\.system\s*\(',
     'HIGH',
     'os.system() is dangerous - use subprocess shell=False'),
    ('Path Traversal',
     r'open\s*\(.*\+.*user|open\s*\(f["\']',
     'HIGH',
     'User-controlled path = path traversal risk'),
    ('.env in Route',
     r'(?i)(@app\.route|@router).*\.env',
     'CRITICAL',
     '.env file served by web = catastrophic'),
    ('Path Traversal',
     r'open\s*\(.*\+.*request|open\s*\(.*input.*\)|path.*join.*input',
     'HIGH',
     'User-controlled file path = path traversal risk'),
    ('Unvalidated MCP URL',
     r'(?i)mcp.*server.*url.*=.*http',
     'HIGH',
     'Unvalidated MCP server URL = external prompt injection risk'),
    ('Hardcoded Admin Creds',
     r'(?i)(admin_user|admin_pass|root_pass)\s*=\s*["\']\w+["\']',
     'CRITICAL',
     'Default admin credentials = backdoor'),
    ('Weak Random for Security',
     r'(?i)(token|password|secret).*random\.random|random\.randint',
     'HIGH',
     'random module is insecure - use secrets.token_hex()'),
    ('YAML Unsafe Load',
     r'yaml\.load\s*\([^,)]+\)',
     'CRITICAL',
     'yaml.load() = RCE possible - use yaml.safe_load()'),
    ('Pickle Loads',
     r'pickle\.loads\s*\(',
     'HIGH',
     'pickle.loads on untrusted data = RCE risk'),
    ('No Rate Limit on Auth',
     r'(?i)@app\.route.*login',
     'MEDIUM',
     'Login endpoint without rate limit = brute force possible'),
    ('Unvalidated File Upload',
     r'(?i)file\.save\s*\(|request\.files.*save',
     'HIGH',
     'File type must be validated before save'),
]